[tox]
# Test against all supported Python versions
envlist = py310, py311, py312,  py313, py314
skip_missing_interpreters = true

[testenv]
deps =
    pytest
    numpy <=2.5.0
passenv =
    CC
    CFLAGS
    LDFLAGS
commands =
    python -m pytest tests/ -v

[testenv:coverage]
deps =
    pytest
    pytest-cov
    numpy <=2.5.0
passenv =
    CC
    CFLAGS
    LDFLAGS
commands =
    python -m pytest tests/ --cov=pyifb --cov-report=html --cov-report=term

[testenv:lint]
deps =
    black
    flake8
skip_install = true
commands =
    black --check --diff pyifb/ tests/
    flake8 pyifb/ tests/

[testenv:build]
deps =
    build
    setuptools>=80
    setuptools_scm[toml]>=9.2
passenv =
    CC
    CFLAGS
    LDFLAGS
skip_install = true
commands =
    python -m build

[testenv:dev]
deps =
    -e .[dev]
passenv =
    CC
    CFLAGS
    LDFLAGS
commands =
    python -c "import pyifb; print('Import successful')"