name: Bandit
on: [push, pull_request]
permissions: {}


jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Perform Bandit Analysis
        shell: bash
        run: |
            python -m pip install bandit[sarif]
            bandit -c pyproject.toml -r . -f sarif -o results.sarif || true
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif