
name: Test on Cygwin 
on: [push, pull_request]
permissions: {}

jobs:
  cygwin:
    runs-on: windows-latest
    steps:
        - run: git config --global core.autocrlf input

        - uses: actions/checkout@v4
          with:
            persist-credentials: false

        - name: Install Cygwin
          uses: cygwin/cygwin-install-action@v5
          with:
            platform: x86_64
            install-dir: 'C:\tools\cygwin'
            packages: >-
              python311-devel python311-pip python-pip-wheel python-setuptools-wheel
              liblapack-devel liblapack0 gcc gcc-fortran git dash

        - name: pip cache
          uses: actions/cache@v4
          with:
            path: 'C:\tools\cygwin\home\runneradmin\.local'
            key: ${{ runner.os }}-${{ hashFiles('pyproject.toml') }} 
                
        - name: Set Windows PATH
          uses: egor-tensin/cleanup-path@v4
          with:
            dirs: 'C:\tools\cygwin\bin;C:\tools\cygwin\lib\lapack'
        - name: Verify that bash is Cygwin bash
          run: |
            command bash
            bash -c "uname -svrmo"
        - name: Tell Cygwin's git about this repository.
          run: |
            dash -c "which git; /usr/bin/git config --system --add safe.directory /cygdrive/d/a/pyifb/pyifb"        
        - name: Verify python version
          # Make sure it's the Cygwin one, not a Windows one
          run: |
            dash -c "which python3.11; /usr/bin/python3.11 --version -V"    
        - name: Install dependencies
          shell: "C:\\tools\\cygwin\\bin\\bash.exe -o igncr -eo pipefail {0}"
          run: |
            /usr/bin/python3.11 -m pip install --upgrade pip
            /usr/bin/python3.11 -m pip install build wheel pip-tools
            /usr/local/bin/pip-compile -o requirements.txt --extra test --strip-extras
            /usr/bin/python3.11 -m pip install -r requirements.txt
        - name: Install 
          shell: "C:\\tools\\cygwin\\bin\\bash.exe -o igncr -eo pipefail {0}"
          run: |
            /usr/bin/python3.11 -m pip install -e .
        - name: Run tests
          shell: "C:\\tools\\cygwin\\bin\\bash.exe -o igncr -eo pipefail {0}"
          run: |
              /usr/bin/python3.11 -m pytest -v
