name: Linux LLVM clang
on: [push, pull_request]
permissions: {}

jobs:
  linux_llvm:
    strategy:
      matrix:
        os: [ubuntu-latest]    
        python-version: ['3.13', '3.14']
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      runs-on: ${{ matrix.os }}
      setup-python-version: ${{ matrix.python-version }}
      system-packages: build-essential cmake ninja-build flang clang libflang-dev libclang-common
      cc: clang
      fc: flang
      build-command: |
        python -m build
        python -m pip install dist/pyifb*.whl
      test-command: pytest -v

