name: Linux Intel
on: [push, pull_request]
permissions: {}

jobs:
  linux_intel:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]    
        python-version: [ '3.13']    
        toolchain:
          - {compiler: intel, version: '2025.0'}
          - {compiler: intel, version: '2024.0'}
          - {compiler: intel, version: '2023.0'}


    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel pip-tools
          pip-compile -o requirements.txt --extra test --strip-extras
          python -m pip install -r requirements.txt
    
      - name: Build
        run: |
          export CC=icc
          python -m build
          python -m pip install dist/pyifb*.whl

  
      - name: Test
        # Don't use python -m pytest as that screws up the module loading
        run: |
          pytest -v

