name: Linux ARM
on: [push, pull_request]
permissions: {}

jobs:
  linux_arm:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-24.04-arm ]
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14'] 
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      runs-on: ${{ matrix.os }}
      setup-python-version: ${{ matrix.python-version }}
      system-packages: gcc gfortran libopenblas-dev
      cc: gcc
      fc: gfortran
      build-command: python -m build
      install-command: python -m pip install dist/pyifb*.whl
      test-command: pytest -v

