name: Linux Intel
on: [push, pull_request]
permissions: {}

jobs:
  linux_intel:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]    
        python-version: [ '3.13']    
        toolchain:
          - {compiler: intel, version: '2025.0'}
          - {compiler: intel, version: '2024.0'}
          - {compiler: intel, version: '2023.0'}
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      runs-on: ${{ matrix.os }}
      setup-python-version: ${{ matrix.python-version }}
      fortran-compiler: ${{ matrix.toolchain.compiler }}
      fortran-version: ${{ matrix.toolchain.version }}
      cc: icx
      fc: ifx
      build-command: python -m build
      install-command: python -m pip install dist/pyifb*.whl
      test-command: pytest -v

