name: Linux GCC
on: [push, pull_request]
permissions: {}

jobs:
  linux_gcc:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]    
        python-version: [ '3.10', '3.11', '3.12', '3.13', '3.14']    
        toolchain:
          - {compiler: gcc, version: 12}
          - {compiler: gcc, version: 13}
          - {compiler: gcc, version: 14}
          - {compiler: gcc, version: 15}
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      runs-on: ${{ matrix.os }}
      setup-python-version: ${{ matrix.python-version }}
      fortran-compiler: ${{ matrix.toolchain.compiler }}
      fortran-version: ${{ matrix.toolchain.version }}
      cc: gcc
      build-command: |
        python -m build
        python -m pip install dist/pyifb*.whl
      test-command: pytest -v

