name: MacOS CI
on: [push, pull_request]
permissions: {}

jobs:
  macos_ci:
    strategy:
      matrix:
        os: [macos-latest, macos-15-intel]    
        python-version: ['3.10', '3.11', '3.12', '3.13','3.14']    
        toolchain:
          - {compiler: gcc, version: 13}
          - {compiler: gcc, version: 14}
          - {compiler: gcc, version: 15}
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      runs-on: ${{ matrix.os }}
      setup-python-version: ${{ matrix.python-version }}
      fortran-compiler: ${{ matrix.toolchain.compiler }}
      fortran-version: ${{ matrix.toolchain.version }}
      use-fortran-outputs: true
      build-command: python -m build
      install-command: python -m pip install dist/pyifb*.whl
      test-command: pytest -v


