name:  PyPy
on: [push, pull_request]
permissions: {}

jobs:
  pypy:
    strategy:
      fail-fast: true
      matrix:
        toolchain:
          - {compiler: gcc, version: 12}
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      runs-on: ubuntu-latest
      setup-python-version: pypy3.10
      python-command: pypy3
      system-packages: libopenblas-dev
      fortran-compiler: ${{ matrix.toolchain.compiler }}
      fortran-version: ${{ matrix.toolchain.version }}
      cc: gcc
      build-command: |
        pypy3 -m build
        pypy3 -m pip install dist/pyifb*.whl
      test-command: pytest -v
