name: windows CI
on: [push, pull_request]
permissions: {}

jobs:
  windows_ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]    
        python-version: [ '3.10', '3.11', '3.12', '3.13']    
        toolchain:
          - {compiler: gcc, version: 12}
          - {compiler: gcc, version: 13}
          - {compiler: gcc, version: 14}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          choco install make
          python -m pip install --upgrade pip
          python -m pip install build wheel pip-tools
          pip-compile -o requirements.txt --extra test --strip-extras
          python -m pip install -r requirements.txt

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
    
      - name: Build
        run: python -m pip install -e .

  
      - name: Test
        run: python -m pytest -v

